import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { dark } from "@clerk/themes";
import ShaderBackground from "@/components/BackGround";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const balooC = localFont({
  src: "./fonts/BalooChettan-Regular.ttf",
  weight: "400",
  style: "normal",
  variable: "--font-baloo",
  display: "swap",
});

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

const vagRounded = localFont({
  src: [
    {
      path: "./fonts/VAG Rounded Next Light.ttf",
      weight: "300",
      style: "light",
    },

    {
      path: "./fonts/VAG Rounded Next Regular.ttf",
      weight: "400",
      style: "normal",
    },

    {
    path: "./fonts/VAG Rounded Next Medium.ttf",
      weight: "400",
      style: "medium",
    
    },
      {
      path: "./fonts/VAG Rounded Next SemiBold.ttf",
      weight: "600",
      style: "semibold",
    },
    
    {
      path: "./fonts/VAG Rounded Next Bold.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "./fonts/VAG Rounded Next Black.ttf",
      weight: "900",
      style: "black",
    }
  ],
  variable: "--font-vag-rounded",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <>
      <ShaderBackground />
      <ClerkProvider
        signInUrl="/sign-in"
        signUpUrl="/sign-up"
        afterSignOutUrl="/sign-in"
        appearance={{
          baseTheme: dark,
        }}
      >
       <html lang="en" className={`${balooC.variable} ${vagRounded.variable}`}>
      <body className="font-sans">{children}</body>
    </html>
        <Toaster />
      </ClerkProvider>
    </>
  );
  
}
