import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { dark } from '@clerk/themes'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const myFont = localFont({
  src: "./fonts/BalooChettan-Regular.ttf",
  variable: "--font-myFont",
});

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

const vagRounded = localFont({
  src: [
    {
      path: "./fonts/VAG_Rounded_Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/fonnts.com-VAG_Rounded_Next_W05_SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/fonnts.com-VAG_Rounded_Next_W05_Bold_It.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/fonnts.com-VAG_Rounded_Next_W05_Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/fonnts.com-VAG_Rounded_Next_W05_ExtraBlack.ttf",
      weight: "950",
      style: "normal",
    },
  ],
  variable: "--font-vag-rounded",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      afterSignOutUrl="/sign-in"
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body
          className={`${myFont.variable} ${vagRounded.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
