import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { dark } from "@clerk/themes";
import ShaderBackground from "@/components/BackGround";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const myFont = localFont({
  src: [
    {
      path: "./fonts/BalooChettan-Regular.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-baloo",
});



export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

const vagRounded = localFont({
  src: [
    {
      path: "./fonts/VAG Rounded Next Light.ttf",
      weight: "300",
      style: "light",
    },
    {
      path: "./fonts/fonnts.com-VAG_Rounded Next SemiBold.ttf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "./fonts/fonnts.com-VAG_Rounded_Next_W05_Bold_It.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "./fonts/fonnts.com-VAG_Rounded_Next_W05_Black.ttf",
      weight: "900",
      style: "black",
    },
    {
      path: "./fonts/fonnts.com-VAG_Rounded_Next_W05_ExtraBlack.ttf",
      weight: "950",
      style: "superblack",
    },
  ],
  variable: "--font-vag-rounded",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <>
      <ShaderBackground />
      <ClerkProvider
        signInUrl="/sign-in"
        signUpUrl="/sign-up"
        afterSignOutUrl="/sign-in"
        appearance={{
          baseTheme: dark,
        }}
      >
        <html lang="en">
          <body
          className={`${myFont.variable} ${vagRounded.variable} antialiased`}
          >
            {children}
          </body>
        </html>
        <Toaster />
      </ClerkProvider>
    </>
  );
  
}
